SEED:
  random_seed: 42

PREPROCESS:
  preprocess_serial:

DATALOADER:
  num_workers: 8
  shuffle:
  pin_memory: True
  drop_last:

DATA:
  max_token: 30

MODEL:
  model_str: vqa_model
  num_targets: 86
  dim_i: 1024
  dim_q: 1024
  dim_h: 1024

TRAIN:
  num_epochs: 6
  batch_size: 128
  learning_rate: 0.000002
  early_stopping_patience: 50
  optimizer:
  scheduler:
  momentum:
  weight_decay: 0.0001
  loss_function: crossentropy
  metric_function: accuracy

PERFORMANCE_RECORD:
  column_list:
    - train_serial
    - train_timestamp
    - model_str
    - optimizer_str
    - loss_function_str
    - metric_function_str
    - early_stopping_patience
    - batch_size
    - epoch
    - learning_rate
    - momentum
    - random_seed # -----------key columns-------------
    - epoch_index 
    - train_loss
    - validation_loss
    - train_score
    - validation_score
    - elapsed_time

